version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - k6-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - k6-network

  k6:
    image: grafana/k6
    container_name: k6
    command: run --out influxdb=http://influxdb:8086/k6 /k6-test.js
    volumes:
      - ./k6-test.js:/k6-test.js
    networks:
      - k6-network

volumes:
  influxdb:
  grafana:

networks:
  k6-network:
    driver: bridge
